# Generated by Django 3.0.5 on 2024-07-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=50, verbose_name='名称')),
                ('pid', models.SmallIntegerField(verbose_name='父id')),
                ('controller', models.CharField(default='', max_length=32, verbose_name='控制器')),
                ('method', models.CharField(default='', max_length=64, verbose_name='操作方法')),
                ('path', models.CharField(blank=True, max_length=32, null=True, verbose_name='全路径')),
                ('level', models.SmallIntegerField(default=0, verbose_name='级别')),
                ('top_menu_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='顶级菜单的id')),
                ('orderby', models.CharField(blank=True, max_length=20, null=True, verbose_name='排序')),
                ('atime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'authority',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='管理员名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('role_id', models.PositiveSmallIntegerField(default=0, verbose_name='角色id')),
                ('supermanager', models.BooleanField(default=False, verbose_name='超级管理员')),
                ('mtime', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('atime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='角色名称')),
                ('authority_id', models.TextField(blank=True, null=True, verbose_name='权限ids,1,2,5')),
                ('controller_method', models.TextField(blank=True, null=True, verbose_name='模块-方法')),
                ('mtime', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('atime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'role',
            },
        ),
    ]
