# Generated by Django 3.2.25 on 2024-07-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8sdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
