# Generated by Django 3.2.25 on 2024-08-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8sdashboard', '0002_auto_20240731_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('managerid', models.IntegerField(default=0, verbose_name='管理员id')),
                ('filename', models.CharField(default='', max_length=180, verbose_name='文件名')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='文件内容')),
                ('mtime', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('atime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '模板',
                'verbose_name_plural': '模板',
                'db_table': 'template',
            },
        ),
    ]
