# Generated by Django 3.0.5 on 2025-08-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8sdashboard', '0003_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('managerid', models.PositiveIntegerField(default=0, verbose_name='管理员id')),
                ('clustername', models.CharField(default='', max_length=180, verbose_name='k8s集群名称')),
                ('server', models.CharField(default='', max_length=280, verbose_name='k8s集群的地址')),
                ('username', models.CharField(default='', max_length=180, verbose_name='k8s用户名称')),
                ('token', models.TextField(blank=True, null=True, verbose_name='用户的token和用户证书key任选一样即可')),
                ('certificate_authority_data', models.TextField(blank=True, null=True, verbose_name='集群证书')),
                ('client_certificate_data', models.TextField(blank=True, null=True, verbose_name='用户的证书')),
                ('client_key_data', models.TextField(blank=True, null=True, verbose_name='用户的key')),
                ('mtime', models.PositiveIntegerField(blank=True, null=True, verbose_name='修改时间')),
                ('atime', models.PositiveIntegerField(blank=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '集群',
                'verbose_name_plural': '集群',
                'db_table': 'clusters',
            },
        ),
    ]
