# Generated by Django 3.2.25 on 2026-09-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k8sdashboard', '0005_alter_manager_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32, unique=True, verbose_name='provider')),
                ('access_key', models.CharField(blank=True, default='', max_length=128, verbose_name='access key')),
                ('secret_key', models.CharField(blank=True, default='', max_length=256, verbose_name='secret key')),
                ('default_region', models.CharField(blank=True, default='', max_length=64, verbose_name='region')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='mtime')),
                ('atime', models.DateTimeField(auto_now_add=True, verbose_name='atime')),
            ],
            options={
                'db_table': 'cloud_credential',
            },
        ),
    ]
