from django.urls import path, re_path
from k8sdashboard import kubernetes
urlpatterns = [
    re_path('^pods/$', kubernetes.pods, name='pods'),
    re_path('^deployments/$', kubernetes.deployments, name='deployments'),
    re_path('^replicasets/$', kubernetes.replicasets, name='replicasets'),
    re_path('^daemonsets/$', kubernetes.daemonsets, name='daemonsets'),
    re_path('^statefulsets/$', kubernetes.statefulsets, name='statefulsets'),
    re_path('^cronjob/$', kubernetes.cronjob, name='cronjob'),
    re_path('^job/$', kubernetes.job, name='job'),
    re_path('^services/$', kubernetes.services, name='services'),
    re_path('^endpoints/$', kubernetes.endpoints, name='endpoints'),
    re_path('^endpointslice/$', kubernetes.endpointslice, name='endpointslice'),
    re_path('^ingress/$', kubernetes.ingress, name='ingress'),
    re_path('^ingressclass/$', kubernetes.ingressclass, name='ingressclass'),
    re_path('^secrets/$', kubernetes.secrets, name='secrets'),
    re_path('^configmaps/$', kubernetes.configmaps, name='configmaps'),
    re_path('^persistentvolumes/$', kubernetes.persistentVolumes, name='persistentvolumes'),
    re_path('^persistentvolumeclaims/$', kubernetes.persistentvolumeclaims, name='persistentvolumeclaims'),
    re_path('^storageclasses/$', kubernetes.storageclasses, name='storageclasses'),
    re_path('^csinodes/$', kubernetes.csinodes, name='csinodes'),
    re_path('^resources/$', kubernetes.resources, name='resources'),
    re_path('^nodes/$', kubernetes.nodes, name='nodes'),
    re_path('^namespaces/$', kubernetes.namespaces, name='namespaces'),
    re_path('^events/$', kubernetes.events, name='events'),
    re_path('^serviceaccounts/$', kubernetes.serviceaccounts, name='serviceaccounts'),
    re_path('^hpa/$', kubernetes.hpa, name='hpa'),
    re_path('^roles/$', kubernetes.roles, name='roles'),
    re_path('^rolebindings/$', kubernetes.rolebindings, name='rolebindings'),
    re_path('^resourcequotas/$', kubernetes.resourcequotas, name='resourcequotas'),
    re_path('^limitranges/$', kubernetes.limitranges, name='limitranges'),
    re_path('^networkpolicies/$', kubernetes.networkpolicies, name='networkpolicies'),
    re_path('^pdb/$', kubernetes.pdb, name='pdb'),
    re_path('^crds/$', kubernetes.crds, name='crds'),
    re_path('^podlogs/(?P<namespace>[^/]+)/(?P<pod_name>[^/]+)/(?P<container_name>[^/]+)/$', kubernetes.podlogs, name='podlogs'),
    # re_path('^addrole$', role.addrole, name='addrole'),
    # re_path(r'^assignpermissions/(?P<id>\d+)/$', role.assignpermissions, name='assignpermissions'),
    # re_path('^updaterole/', role.updaterole),
]